services:

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: ${GROQ_MODEL:-llama-3.3-70b-versatile}
      WORKSPACE_DIR: /app/workspace
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    volumes:
      - workspace_data:/app/workspace
    ports:
      - "8000:8000"

volumes:
  workspace_data:
